 

const API = [
  {
    "id": 1,
    "name": "Dr. Aarav Sharma",
    "treats": ["Heart Disease", "Heart Attack", "High Blood Pressure"],
    "specialty": "Cardiology",
    "city": "Mumbai",
    "phone": "+91-9000000001",
    "experience": "15 years",
    "day": "Monday",
    "timing": "11:00 AM - 01:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-j-m-dua.png.webp?itok=7y8dedJj"
  },
  {
    "id": 2,
    "name": "Dr. Meera Gupta",
    "treats": ["Acne", "Eczema", "Skin Allergy"],
    "specialty": "Dermatology",
    "city": "Delhi",
    "phone": "+91-9000000002",
    "experience": "12 years",
    "day": "Tuesday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-sheroo-zamindar_0.png.webp?itok=8cfpPEwO"
  },
  {
    "id": 3,
    "name": "Dr. Rohan Iyer",
    "treats": ["Migraine", "Epilepsy", "Stroke"],
    "specialty": "Neurology",
    "city": "Kolkata",
    "phone": "+91-9000000003",
    "experience": "18 years",
    "day": "Wednesday",
    "timing": "10:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-04/dr-kalyanpury-jawaharlal-choudhury-anaesthesiology-and-painmanagement-in-delhi.png.webp?itok=-O3OKdwB"
  },
  {
    "id": 4,
    "name": "Dr. Ananya Singh",
    "treats": ["Fever", "Child Infection", "Vaccination"],
    "specialty": "Pediatrics",
    "city": "Chennai",
    "phone": "+91-9000000004",
    "experience": "9 years",
    "day": "Thursday",
    "timing": "09:00 AM - 11:00 AM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2026-01/kamal.jpg.webp?itok=CIXCn9Vp"
  },
  {
    "id": 5,
    "name": "Dr. Vikram Patel",
    "treats": ["Fracture", "Joint Pain", "Arthritis"],
    "specialty": "Orthopedics",
    "city": "Ahmedabad",
    "phone": "+91-9000000005",
    "experience": "14 years",
    "day": "Friday",
    "timing": "04:00 PM - 06:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-r-n-srivastava.png.webp?itok=pxD95pOf"
  },
  {
    "id": 6,
    "name": "Dr. Sneha Rao",
    "treats": ["PCOS", "Pregnancy Care", "Infertility"],
    "specialty": "Gynecology",
    "city": "Hyderabad",
    "phone": "+91-9000000006",
    "experience": "11 years",
    "day": "Saturday",
    "timing": "02:00 PM - 04:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-shakti-bhan-khanna.png.webp?itok=E9wRx46L"
  },

  {
    "id": 7,
    "name": "Dr. Karan Mehta",
    "treats": ["Depression", "Anxiety", "Sleep Disorder"],
    "specialty": "Psychiatry",
    "city": "Pune",
    "phone": "+91-9000000007",
    "experience": "16 years",
    "day": "Monday",
    "timing": "03:00 PM - 06:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-soundara-pandian-p.png.webp?itok=HluyvkGB"
  },
  {
    "id": 8,
    "name": "Dr. Priya Reddy",
    "treats": ["Diabetes", "Thyroid", "Hormonal Imbalance"],
    "specialty": "Endocrinology",
    "city": "Bangalore",
    "phone": "+91-9000000008",
    "experience": "13 years",
    "day": "Tuesday",
    "timing": "09:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-alaka-goswami.png.webp?itok=Ct8jF5JC"
  },
  {
    "id": 9,
    "name": "Dr. Arjun Das",
    "treats": ["Cancer", "Chemotherapy", "Tumor"],
    "specialty": "Oncology",
    "city": "Lucknow",
    "phone": "+91-9000000009",
    "experience": "19 years",
    "day": "Wednesday",
    "timing": "01:00 PM - 04:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-09/dr-amit-gupta-nephrologist-in-lucknow.jpg.webp?itok=jnrTP7y6"
  },
  {
    "id": 10,
    "name": "Dr. Nisha Kapoor",
    "treats": ["X-Ray", "MRI", "CT Scan"],
    "specialty": "Radiology",
    "city": "Jaipur",
    "phone": "+91-9000000010",
    "experience": "17 years",
    "day": "Thursday",
    "timing": "10:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-01/dr-desai-a-pediatrics-in-chennai.png.webp?itok=glIz0Z14"
  },

  {
    "id": 11,
    "name": "Dr. Rahul Jain",
    "treats": ["Heart Disease", "Heart Attack", "High Blood Pressure"],
    "specialty": "Cardiology",
    "city": "Indore",
    "phone": "+91-9000000011",
    "experience": "10 years",
    "day": "Friday",
    "timing": "11:00 AM - 03:00 PM",
    "photo": "..."
  },

  {
    "id": 12,
    "name": "Dr. Kavya Nair",
    "treats": ["Acne", "Psoriasis", "Skin Infection"],
    "specialty": "Dermatology",
    "city": "Bhopal",
    "phone": "+91-9000000012",
    "experience": "8 years",
    "day": "Saturday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-09/dr-vasanthi-d.jpg.webp?itok=Lz2W3gQA"
  },
    {
    "id": 13,
    "name": "Dr. Sandeep Verma",
    "treats": ["Migraine", "Stroke", "Brain Tumor"],
    "specialty": "Neurology",
    "city": "Nagpur",
    "phone": "+91-9000000013",
    "experience": "20 years",
    "day": "Monday",
    "timing": "09:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-09/dr-5.png.webp?itok=wPzabtJI"
  },
  {
    "id": 14,
    "name": "Dr. Isha Malhotra",
    "treats": ["Fever", "Cold", "Child Allergy"],
    "specialty": "Pediatrics",
    "city": "Chandigarh",
    "phone": "+91-9000000014",
    "experience": "7 years",
    "day": "Tuesday",
    "timing": "10:00 AM - 01:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-subhashini-prabhakar_0.png.webp?itok=zQk4YbM8"
  },
  {
    "id": 15,
    "name": "Dr. Manish Tiwari",
    "treats": ["Back Pain", "Fracture", "Joint Replacement"],
    "specialty": "Orthopedics",
    "city": "Surat",
    "phone": "+91-9000000015",
    "experience": "16 years",
    "day": "Wednesday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-mahesh-goenka.png.webp?itok=sciJh2HS"
  },
  {
    "id": 16,
    "name": "Dr. Gokul Nath",
    "treats": ["Pregnancy", "Menstrual Issues", "PCOS"],
    "specialty": "Gynecology",
    "city": "Patna",
    "phone": "+91-9000000016",
    "experience": "21 years",
    "day": "Thursday",
    "timing": "11:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-gokul-nath.png.webp?itok=2-FmN2BH"
  },
  {
    "id": 17,
    "name": "Dr. Amit Chatterjee",
    "treats": ["Stress", "Depression", "Phobia"],
    "specialty": "Psychiatry",
    "city": "Ranchi",
    "phone": "+91-9000000017",
    "experience": "14 years",
    "day": "Friday",
    "timing": "04:00 PM - 07:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-06/dr-puneet-bedi.jpg.webp?itok=jXBjWb_Q"
  },
  {
    "id": 18,
    "name": "Dr. Pooja Yadav",
    "treats": ["Diabetes", "Thyroid", "Obesity"],
    "specialty": "Endocrinology",
    "city": "Raipur",
    "phone": "+91-9000000018",
    "experience": "12 years",
    "day": "Saturday",
    "timing": "09:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-01/dr-monica-chib-psychiatry-in-delhi.png.webp?itok=GnsOBgwv"
  },
  {
    "id": 19,
    "name": "Dr. M S Kanwar",
    "treats": ["Lung Cancer", "Breast Cancer", "Chemotherapy"],
    "specialty": "Oncology",
    "city": "Goa",
    "phone": "+91-9000000019",
    "experience": "25 years",
    "day": "Monday",
    "timing": "01:00 PM - 04:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-m-s-kanwar.png.webp?itok=ut5fJX-u"
  },
  {
    "id": 20,
    "name": "Dr. Ritu Bansal",
    "treats": ["MRI", "CT Scan", "Ultrasound"],
    "specialty": "Radiology",
    "city": "Amritsar",
    "phone": "+91-9000000020",
    "experience": "15 years",
    "day": "Tuesday",
    "timing": "10:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-10/dr-raghupathi-rao-nandanavanam.png.webp?itok=D1jg3bWi"
  },
  {
    "id": 21,
    "name": "Dr. Aditya Roy",
    "treats": ["Heart Failure", "Angina", "Hypertension"],
    "specialty": "Cardiology",
    "city": "Mumbai",
    "phone": "+91-9000000021",
    "experience": "13 years",
    "day": "Wednesday",
    "timing": "03:00 PM - 06:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-v-k-aneja.png.webp?itok=uAgTvOng"
  },
  {
    "id": 22,
    "name": "Dr. Shreya Bose",
    "treats": ["Acne", "Skin Rash", "Dermatitis"],
    "specialty": "Dermatology",
    "city": "Delhi",
    "phone": "+91-9000000022",
    "experience": "10 years",
    "day": "Thursday",
    "timing": "09:00 AM - 11:00 AM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-sohan-lal-broor.png.webp?itok=QHxg28ml"
  },
  {
    "id": 23,
    "name": "Dr. Nikhil Menon",
    "treats": ["Epilepsy", "Nerve Pain", "Stroke"],
    "specialty": "Neurology",
    "city": "Kolkata",
    "phone": "+91-9000000023",
    "experience": "17 years",
    "day": "Friday",
    "timing": "11:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-tarun-sahni.png.webp?itok=YAkA-ONq"
  },
  {
    "id": 24,
    "name": "Dr. Vincent Thamburaj",
    "treats": ["Vaccination", "Child Fever", "Nutrition"],
    "specialty": "Pediatrics",
    "city": "Chennai",
    "phone": "+91-9000000024",
    "experience": "22 years",
    "day": "Saturday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-vincent-thamburaj.png.webp?itok=R_Wv52tb"
  },
  {
    "id": 25,
    "name": "Dr. Rohit Khanna",
    "treats": ["Arthritis", "Fracture", "Knee Pain"],
    "specialty": "Orthopedics",
    "city": "Bangalore",
    "phone": "+91-9000000025",
    "experience": "11 years",
    "day": "Monday",
    "timing": "10:00 AM - 01:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-vinod-sukhija.png.webp?itok=d1Vd712C"
  },
  {
    "id": 26,
    "name": "Dr. Jagadeesapandian P",
    "treats": ["Pregnancy Care", "Infertility", "Menstrual Pain"],
    "specialty": "Gynecology",
    "city": "Hyderabad",
    "phone": "+91-9000000026",
    "experience": "19 years",
    "day": "Tuesday",
    "timing": "03:00 PM - 06:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-06/dr-suresh-kr-rawat-youtube-06-06-2025_03_51_pm.png.webp?itok=blCtFTgc"
  },
  {
    "id": 27,
    "name": "Dr. Vivek Arora",
    "treats": ["Anxiety", "Depression", "Insomnia"],
    "specialty": "Psychiatry",
    "city": "Pune",
    "phone": "+91-9000000027",
    "experience": "12 years",
    "day": "Wednesday",
    "timing": "09:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-jagadeesapandian-p.png.webp?itok=KoDI_izU"
  },
  {
    "id": 28,
    "name": "Dr. Ashok Dutta",
    "treats": ["Thyroid", "Hormone Disorder", "Diabetes"],
    "specialty": "Endocrinology",
    "city": "Ahmedabad",
    "phone": "+91-9000000028",
    "experience": "18 years",
    "day": "Thursday",
    "timing": "11:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-ashok-dutta.png.webp?itok=uN3A2x-Y"
  },
  {
    "id": 29,
    "name": "Dr. Harsh Vardhan",
    "treats": ["Tumor", "Chemotherapy", "Cancer Surgery"],
    "specialty": "Oncology",
    "city": "Jaipur",
    "phone": "+91-9000000029",
    "experience": "20 years",
    "day": "Friday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-alok-kumar-agarwal.png.webp?itok=z2sujB75"
  },
  {
    "id": 30,
    "name": "Dr. Balachandar T G",
    "treats": ["X-Ray", "CT Scan", "MRI"],
    "specialty": "Radiology",
    "city": "Lucknow",
    "phone": "+91-9000000030",
    "experience": "23 years",
    "day": "Saturday",
    "timing": "10:00 AM - 01:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-balachandar-t-g.png.webp?itok=FWCA58ee"
  },
  {
    "id": 31,
    "name": "Dr. Mohit Agarwal",
    "treats": ["Heart Attack", "Heart Failure", "Hypertension"],
    "specialty": "Cardiology",
    "city": "Indore",
    "phone": "+91-9000000031",
    "experience": "14 years",
    "day": "Monday",
    "timing": "01:00 PM - 04:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-d-k-bhargava.png.webp?itok=FWJA0s7x"
  },
  {
    "id": 32,
    "name": "Dr. Anjali Mehra",
    "treats": ["Skin Allergy", "Eczema", "Psoriasis"],
    "specialty": "Dermatology",
    "city": "Bhopal",
    "phone": "+91-9000000032",
    "experience": "9 years",
    "day": "Tuesday",
    "timing": "09:00 AM - 11:00 AM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-04/Dr%20Vinita%20Das.webp?itok=4CXnRdGq"
  },
  {
    "id": 33,
    "name": "Dr. Saurabh Nanda",
    "treats": ["Migraine", "Stroke", "Brain Injury"],
    "specialty": "Neurology",
    "city": "Nagpur",
    "phone": "+91-9000000033",
    "experience": "16 years",
    "day": "Wednesday",
    "timing": "03:00 PM - 06:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-05/dr-mahesh-chandra-garg.jpg.webp?itok=DGtChBpf"
  },
  {
    "id": 34,
    "name": "Dr. Kriti Sethi",
    "treats": ["Cold", "Fever", "Child Infection"],
    "specialty": "Pediatrics",
    "city": "Chandigarh",
    "phone": "+91-9000000034",
    "experience": "8 years",
    "day": "Thursday",
    "timing": "10:00 AM - 01:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-12/dr-harmeet-malhotra.jpg.webp?itok=oGHMx9zP"
  },
  {
    "id": 35,
    "name": "Dr. Yash Malviya",
    "treats": ["Joint Pain", "Fracture", "Spine Pain"],
    "specialty": "Orthopedics",
    "city": "Surat",
    "phone": "+91-9000000035",
    "experience": "11 years",
    "day": "Friday",
    "timing": "02:00 PM - 05:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-satishchandra-p.png.webp?itok=nwGY34kg"
  },
  {
    "id": 36,
    "name": "Dr. Samir Sahu",
    "treats": ["PCOS", "Pregnancy", "Infertility"],
    "specialty": "Gynecology",
    "city": "Patna",
    "phone": "+91-9000000036",
    "experience": "13 years",
    "day": "Saturday",
    "timing": "11:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-samir-sahu.png.webp?itok=1kAYCzrl"
  },
  {
    "id": 37,
    "name": "Dr. Kunal Bhatt",
    "treats": ["Stress", "Anxiety", "Depression"],
    "specialty": "Psychiatry",
    "city": "Ranchi",
    "phone": "+91-9000000037",
    "experience": "10 years",
    "day": "Monday",
    "timing": "04:00 PM - 07:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-rajendiran-n_0.png.webp?itok=M3cqXMyL"
  },
  {
    "id": 38,
    "name": "Dr. Poonam Rawat",
    "treats": ["Diabetes", "Hormone Disorder", "Obesity"],
    "specialty": "Endocrinology",
    "city": "Raipur",
    "phone": "+91-9000000038",
    "experience": "15 years",
    "day": "Tuesday",
    "timing": "09:00 AM - 12:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-01/dr-ranjana-sharma-obstetrics-and-gynecology-in-delhi.png.webp?itok=GM5qcxo9"
  },
  {
    "id": 39,
    "name": "Dr. Arvind Iqbal",
    "treats": ["Lung Cancer", "Tumor", "Chemotherapy"],
    "specialty": "Oncology",
    "city": "Goa",
    "phone": "+91-9000000039",
    "experience": "18 years",
    "day": "Wednesday",
    "timing": "01:00 PM - 04:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-madhu-roy.png.webp?itok=kSXTqKob"
  },
  {
    "id": 40,
    "name": "Dr. Muraleedharan A",
    "treats": ["MRI", "Ultrasound", "CT Scan"],
    "specialty": "Radiology",
    "city": "Amritsar",
    "phone": "+91-9000000040",
    "experience": "22 years",
    "day": "Thursday",
    "timing": "10:00 AM - 02:00 PM",
    "photo": "https://drupal-cdn-hfaeddcdbng5hfbg.a01.azurefd.net/sites/default/files/styles/doctor_card/public/2025-07/dr-muraleedharan-a.png.webp?itok=gnvH-lWO"
  }
];
module.exports = API;
